# Generated by Django 5.1.2 on 2024-12-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=0, verbose_name="在庫"),
        ),
    ]
