# Generated by Django 5.1.2 on 2024-12-01 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_product_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
